name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: latest
        
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Provision Infra with Terraform 
        run: ./provision.sh

      - name: Get Key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.PRIVATE_KEY_EC2 }}" > ~/.ssh/study
          chmod 600 ~/.ssh/study
  
      - name: 
        run: ./test-ssh-to-ec2.sh

      - name: Alert on test failure
        if: failure()
        run: |
          # Send alert (e.g., Slack notification, email) on test failure

  destroy:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: latest
        
      - name: Destroy infrastructure
        run: ./destroy.sh
