name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: latest
        
      - name: Set up Keys
        run: |
            mkdir ~/.ssh
            echo "${{ secrets.PRIVATE_KEY_EC2 }}" > ~/.ssh/study
            chmod 600 ~/.ssh/study
            echo "${{ secrets.PUBLIC_KEY_EC2 }}" > ~/.ssh/study.pub
            chmod 400 ~/.ssh/study.pub
            
      - name: Provision Infra with Terraform 
        run: ./provision.sh

      
      - name: 
        run: ./test-ssh-to-ec2.sh

      - name: Alert on test failure
        if: failure()
        run: |
          # Send alert (e.g., Slack notification, email) on test failure

  destroy:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: latest
        
      - name: Destroy infrastructure
        run: ./destroy.sh
