name: Test ENV

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: false
        default: DEV

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Test ENV
      run: echo "ENVIRONMENT=${{ env.ENVIRONMENT }}"
