name: Test Environment Variables

on:
  push:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (e.g., dev, test, prod)'
        type: string
        required: true
        default: dev

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || github.ref == 'refs/heads/dev' && 'dev' || github.ref == 'refs/heads/test' && 'test' || 'prod' }}
    env:
      MY_APP_NAME: ${{ vars.APP_NAME }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo ENVIRONMENT
      run: echo "ENVIRONMENT=${{ env.ENVIRONMENT }}"
    - name: Echo var.APP_NAME
      run: echo "APP_NAME=${{ vars.APP_NAME }}"
    - name: Echo MY_APP_NAME
      run: echo "MY_APP_NAME=$MY_APP_NAME"
    