name: Test SSH Connection

on: [push]

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up SSH
      run: echo "$PRIVATE_KEY" > private-key.pem && chmod 600 private-key.pem

    - name: Run SSH test
      run: |
        ./test_ssh.sh
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
