name: Test Environment Variables

on:
  push:
    branches: [main, dev]
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
        default: dev

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/dev' && 'dev' || github.ref == 'refs/heads/test' && 'test' || 'prod' }}
    env:
      ENVIRONMENT_FROM_INPUT: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Echo ENVIRONMENT_FROM_INPUT
      run: echo "ENVIRONMENT_FROM_INPUT=${{ env.ENVIRONMENT_FROM_INPUT }}"
    - name: Echo APP_NAME
      run: echo "APP_NAME=$APP_NAME"
    - name: Echo var.APP_NAME
      run: echo "APP_NAME=${{ vars.APP_NAME }}"
